spring.application.name=cart-service
server.port=8083

# Security auto-configuration exclusion
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/eshoppingzone_cart
spring.datasource.username=root
spring.datasource.password=Siva@2710

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.hostname=localhost
eureka.instance.ip-address=127.0.0.1
eureka.instance.prefer-ip-address=true
